CREATE TABLE Empregado (
    Nome_Empregado VARCHAR(50) CONSTRAINT EP_NM_NN NOT NULL,
    Rua VARCHAR(100) CONSTRAINT EP_RUA_NN NOT NULL,
    Cidade VARCHAR(30),
    Estado_Civil VARCHAR(15)
);

ALTER TABLE Empregado
ADD Salario NUMERIC(11,2);

ALTER TABLE Empregado
ADD data_nascimento DATE;

ALTER TABLE Empregado
MODIFY Cidade VARCHAR(110);

CREATE TABLE Companhia (
    Nome_Companhia VARCHAR(50) CONSTRAINT CIA_NM_PK PRIMARY KEY,
    Cidade VARCHAR(30)
);

ALTER TABLE Empregado
MODIFY Nome_Empregado varchar(50) CONSTRAINT EP_NM_PK PRIMARY KEY

CREATE TABLE Trabalha (
  Nome_Empregado VARCHAR(50) CONSTRAINT TB_EP_PK PRIMARY KEY REFERENCES Empregado,
  Nome_Companhia VARCHAR(50) CONSTRAINT TB_NM_NN NOT NULL REFERENCES Companhia,
  Salario NUMERIC(9,2) CONSTRAINT TB_SL_NN NOT NULL
);

CREATE TABLE Gerente (
  Nome_Empregado VARCHAR(50) CONSTRAINT GE_NMEM_NN NOT NULL REFERENCES Empregado,
  Nome_Gerente VARCHAR(50) CONSTRAINT GE_NMGE_NN NOT NULL REFERENCES Empregado
);

DROP TABLE Gerente;
DROP TABLE Trabalha;
DROP TABLE Companhia;
DROP TABLE Empregado;
